"""menambahkan field baru pada mws

Revision ID: 1c6145e6345f
Revises: 666afe0f26b4
Create Date: 2025-08-10 11:13:32.344673

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1c6145e6345f'
down_revision = '666afe0f26b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mws_parts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('capability', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('iwoDate', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('workSheetDate', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('finish_date2', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('men_powers', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('men_hours', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('document_penyerta', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('isrNo', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('remark', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mws_parts', schema=None) as batch_op:
        batch_op.drop_column('remark')
        batch_op.drop_column('isrNo')
        batch_op.drop_column('document_penyerta')
        batch_op.drop_column('men_hours')
        batch_op.drop_column('men_powers')
        batch_op.drop_column('finish_date2')
        batch_op.drop_column('workSheetDate')
        batch_op.drop_column('iwoDate')
        batch_op.drop_column('capability')


    # ### end Alembic commands ###
