"""tambah tabel di mws

Revision ID: 2499945aa7f9
Revises: 712380954fc7
Create Date: 2025-08-06 18:04:45.619397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2499945aa7f9'
down_revision = '712380954fc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mws_parts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ref_logistic_ppc', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('mdr_doc_defect', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('remark_mws', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('test_result', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('schedule_delivery_on_time', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('ecd_finish_workdays', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('selisih_work_days', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('prosentase_schedule', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('form_out_no', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('tanda_terima_fo_no', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('tanda_terima_fo_date', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('stripping_report_date', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('stripping_order_by_sap_date', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('prosentase_bdp', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('qty_bdp', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('selisih_order_work_days', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('time_stripping_work_days', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('max_stripping_date', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('tase_stripping', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('status_s_us', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('ship_transfer_tt_date', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('ship_transfer_tt_no', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('selisih_shipping_work_days', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('tase', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mws_parts', schema=None) as batch_op:
        batch_op.drop_column('tase')
        batch_op.drop_column('selisih_shipping_work_days')
        batch_op.drop_column('ship_transfer_tt_no')
        batch_op.drop_column('ship_transfer_tt_date')
        batch_op.drop_column('status_s_us')
        batch_op.drop_column('tase_stripping')
        batch_op.drop_column('max_stripping_date')
        batch_op.drop_column('time_stripping_work_days')
        batch_op.drop_column('selisih_order_work_days')
        batch_op.drop_column('qty_bdp')
        batch_op.drop_column('prosentase_bdp')
        batch_op.drop_column('stripping_order_by_sap_date')
        batch_op.drop_column('stripping_report_date')
        batch_op.drop_column('tanda_terima_fo_date')
        batch_op.drop_column('tanda_terima_fo_no')
        batch_op.drop_column('form_out_no')
        batch_op.drop_column('prosentase_schedule')
        batch_op.drop_column('selisih_work_days')
        batch_op.drop_column('ecd_finish_workdays')
        batch_op.drop_column('schedule_delivery_on_time')
        batch_op.drop_column('test_result')
        batch_op.drop_column('remark_mws')
        batch_op.drop_column('mdr_doc_defect')
        batch_op.drop_column('ref_logistic_ppc')

    # ### end Alembic commands ###
