"""add kolomto Text to store a JSON list of NIKs 

Revision ID: 2907a41c525f
Revises: a190f994c9d7
Create Date: 2025-07-29 10:53:35.858168

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2907a41c525f'
down_revision = 'a190f994c9d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mws_parts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_mechanics', sa.Text(), nullable=True))

    with op.batch_alter_table('mws_steps', schema=None) as batch_op:
        batch_op.alter_column('man',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mws_steps', schema=None) as batch_op:
        batch_op.alter_column('man',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)

    with op.batch_alter_table('mws_parts', schema=None) as batch_op:
        batch_op.drop_column('assigned_mechanics')

    # ### end Alembic commands ###
