"""perubahan pada tabel user

Revision ID: 42028c611b2a
Revises: b6bc3cc7dd76
Create Date: 2025-08-07 11:15:28.535570

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '42028c611b2a'
down_revision = 'b6bc3cc7dd76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff_areas', schema=None) as batch_op:
        batch_op.alter_column('assigned_customer',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff_areas', schema=None) as batch_op:
        batch_op.alter_column('assigned_customer',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###
