"""ubah stripping deadline jadi max stripping deadline

Revision ID: 6444899e2866
Revises: 1c6145e6345f
Create Date: 2025-08-10 16:36:09.990241

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6444899e2866'
down_revision = '1c6145e6345f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mws_parts', schema=None) as batch_op:
        batch_op.alter_column('max_stripping_date',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.Date(),
               existing_nullable=True)
        batch_op.drop_column('stripping_deadline')
      

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mws_parts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripping_deadline', sa.DATE(), nullable=True))
        batch_op.alter_column('max_stripping_date',
               existing_type=sa.Date(),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###
