"""menambahkan field baru 

Revision ID: 666afe0f26b4
Revises: d7debccc922c
Create Date: 2025-08-10 10:10:41.415925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '666afe0f26b4'
down_revision = 'd7debccc922c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Corrected: Removed server_default='[]' to comply with MySQL limitations for TEXT columns.
    with op.batch_alter_table('mws_steps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attachments', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mws_steps', schema=None) as batch_op:
        batch_op.drop_column('attachments')
    # ### end Alembic commands ###