"""perubahaan tabel user

Revision ID: 712380954fc7
Revises: 928949e48add
Create Date: 2025-08-06 13:34:08.936567

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '712380954fc7'
down_revision = '928949e48add'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff_areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nik', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('assigned_customer', sa.String(length=100), nullable=True),
    sa.Column('assigned_shop_area', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('assigned_customer')
        batch_op.drop_column('assigned_shop_area')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_shop_area', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('assigned_customer', mysql.VARCHAR(length=100), nullable=True))

    op.drop_table('staff_areas')
    # ### end Alembic commands ###
