"""rename columns to UPPER + spaces

Revision ID: 8bce897896b4
Revises: 6444899e2866
Create Date: 2025-08-10 16:47:53.918594

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8bce897896b4'
down_revision = '6444899e2866'
branch_labels = None
depends_on = None


def upgrade():
    """rename columns to UPPER + spaces"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mws_parts', schema=None) as batch_op:
        # Rename all columns first
        batch_op.alter_column('partNumber', new_column_name='PART NUMBER', existing_type=sa.String(length=100), nullable=False)
        batch_op.alter_column('serialNumber', new_column_name='SERIAL NUMBER', existing_type=sa.String(length=100), nullable=False)
        batch_op.alter_column('tittle', new_column_name='TITTLE', existing_type=sa.String(length=255), nullable=False)
        batch_op.alter_column('jobType', new_column_name='JOB TYPE', existing_type=sa.String(length=100), nullable=True)
        batch_op.alter_column('ref', new_column_name='REF', existing_type=sa.String(length=100), nullable=True)
        batch_op.alter_column('customer', new_column_name='CUSTOMER', existing_type=sa.String(length=100), nullable=True)
        batch_op.alter_column('acType', new_column_name='AC TYPE', existing_type=sa.String(length=100), nullable=True)
        batch_op.alter_column('wbsNo', new_column_name='WBS NO', existing_type=sa.String(length=100), nullable=True)
        batch_op.alter_column('worksheetNo', new_column_name='WORKSHEET NO', existing_type=sa.String(length=100), nullable=True)
        batch_op.alter_column('iwoNo', new_column_name='IWO NO', existing_type=sa.String(length=100), nullable=True)
        batch_op.alter_column('shopArea', new_column_name='SHOP AREA', existing_type=sa.String(length=100), nullable=True)
        batch_op.alter_column('revision', new_column_name='REVISION', existing_type=sa.String(length=50), nullable=True)
        batch_op.alter_column('status', new_column_name='STATUS', existing_type=sa.String(length=50), nullable=True)
        batch_op.alter_column('currentStep', new_column_name='CURRENT STEP', existing_type=sa.Integer(), nullable=True)
        batch_op.alter_column('startDate', new_column_name='START DATE', existing_type=sa.Date(), nullable=True)
        batch_op.alter_column('finishDate', new_column_name='FINISH DATE', existing_type=sa.Date(), nullable=True)
        batch_op.alter_column('preparedBy', new_column_name='PREPARED BY', existing_type=sa.String(length=100), nullable=True)
        batch_op.alter_column('preparedDate', new_column_name='PREPARED DATE', existing_type=sa.String(length=100), nullable=True)
        batch_op.alter_column('approvedBy', new_column_name='APPROVED BY', existing_type=sa.String(length=100), nullable=True)
        batch_op.alter_column('approvedDate', new_column_name='APPROVED DATE', existing_type=sa.String(length=100), nullable=True)
        batch_op.alter_column('verifiedBy', new_column_name='VERIFIED BY', existing_type=sa.String(length=100), nullable=True)
        batch_op.alter_column('verifiedDate', new_column_name='VERIFIED DATE', existing_type=sa.String(length=100), nullable=True)
        batch_op.alter_column('is_urgent', new_column_name='IS URGENT', existing_type=sa.Boolean(), nullable=True)
        batch_op.alter_column('urgent_request', new_column_name='URGENT REQUEST', existing_type=sa.Boolean(), nullable=True)
        batch_op.alter_column('urgent_request_by', new_column_name='URGENT REQUEST BY', existing_type=sa.String(length=50), nullable=True)
        batch_op.alter_column('max_stripping_date', new_column_name='MAX STRIPPING DATE', existing_type=sa.Date(), nullable=True)
        batch_op.alter_column('stripping_notified', new_column_name='STRIPPING NOTIFIED', existing_type=sa.Boolean(), nullable=True)
        batch_op.alter_column('total_duration', new_column_name='TOTAL DURATION', existing_type=sa.String(length=50), nullable=True)
        batch_op.alter_column('created_at', new_column_name='CREATED AT', existing_type=sa.DateTime(), nullable=True)
        batch_op.alter_column('updated_at', new_column_name='UPDATED AT', existing_type=sa.DateTime(), nullable=True)
        batch_op.alter_column('ref_logistic_ppc', new_column_name='REF LOGISTIC PPC', existing_type=sa.String(length=100), nullable=True)
        batch_op.alter_column('mdr_doc_defect', new_column_name='MDR DOC DEFECT', existing_type=sa.String(length=100), nullable=True)
        batch_op.alter_column('capability', new_column_name='CAPABILITY', existing_type=sa.String(length=100), nullable=True)
        batch_op.alter_column('iwoDate', new_column_name='IWO DATE', existing_type=sa.String(length=100), nullable=True)
        batch_op.alter_column('remark_mws', new_column_name='REMARK MWS', existing_type=sa.String(length=100), nullable=True)
        batch_op.alter_column('test_result', new_column_name='TEST RESULT', existing_type=sa.String(length=100), nullable=True)
        batch_op.alter_column('schedule_delivery_on_time', new_column_name='SCHEDULE DELIVERY ON TIME', existing_type=sa.String(length=100), nullable=True)
        batch_op.alter_column('ecd_finish_workdays', new_column_name='ECD FINISH WORKDAYS', existing_type=sa.String(length=100), nullable=True)
        batch_op.alter_column('selisih_work_days', new_column_name='SELISIH WORK DAYS', existing_type=sa.String(length=100), nullable=True)
        batch_op.alter_column('prosentase_schedule', new_column_name='PROSENTASE SCHEDULE', existing_type=sa.String(length=100), nullable=True)
        batch_op.alter_column('workSheetDate', new_column_name='WORKSHEET DATE', existing_type=sa.String(length=100), nullable=True)
        batch_op.alter_column('form_out_no', new_column_name='FORM OUT NO', existing_type=sa.String(length=100), nullable=True)
        batch_op.alter_column('tanda_terima_fo_no', new_column_name='TANDA TERIMA FO NO', existing_type=sa.String(length=100), nullable=True)
        batch_op.alter_column('tanda_terima_fo_date', new_column_name='TANDA TERIMA FO DATE', existing_type=sa.String(length=100), nullable=True)
        batch_op.alter_column('stripping_report_date', new_column_name='STRIPPING REPORT DATE', existing_type=sa.String(length=100), nullable=True)
        batch_op.alter_column('stripping_order_by_sap_date', new_column_name='STRIPPING ORDER BY SAP DATE', existing_type=sa.String(length=100), nullable=True)
        batch_op.alter_column('prosentase_bdp', new_column_name='PROSENTASE BDP', existing_type=sa.String(length=100), nullable=True)
        batch_op.alter_column('qty_bdp', new_column_name='QTY BDP', existing_type=sa.String(length=100), nullable=True)
        batch_op.alter_column('selisih_order_work_days', new_column_name='SELISIH ORDER WORK DAYS', existing_type=sa.String(length=100), nullable=True)
        batch_op.alter_column('time_stripping_work_days', new_column_name='TIME STRIPPING WORK DAYS', existing_type=sa.String(length=100), nullable=True)
        batch_op.alter_column('tase_stripping', new_column_name='TASE STRIPPING', existing_type=sa.String(length=100), nullable=True)
        batch_op.alter_column('status_s_us', new_column_name='STATUS S US', existing_type=sa.String(length=100), nullable=True)
        batch_op.alter_column('finish_date2', new_column_name='FINISH DATE 2', existing_type=sa.String(length=100), nullable=True)
        batch_op.alter_column('men_powers', new_column_name='MEN POWERS', existing_type=sa.String(length=100), nullable=True)
        batch_op.alter_column('men_hours', new_column_name='MEN HOURS', existing_type=sa.String(length=100), nullable=True)
        batch_op.alter_column('document_penyerta', new_column_name='DOCUMENT PENYERTA', existing_type=sa.String(length=100), nullable=True)
        batch_op.alter_column('ship_transfer_tt_date', new_column_name='SHIP TRANSFER TT DATE', existing_type=sa.String(length=100), nullable=True)
        batch_op.alter_column('ship_transfer_tt_no', new_column_name='SHIP TRANSFER TT NO', existing_type=sa.String(length=100), nullable=True)
        batch_op.alter_column('isrNo', new_column_name='ISR NO', existing_type=sa.String(length=100), nullable=True)
        batch_op.alter_column('selisih_shipping_work_days', new_column_name='SELISIH SHIPPING WORK DAYS', existing_type=sa.String(length=100), nullable=True)
        batch_op.alter_column('tase', new_column_name='TASE', existing_type=sa.String(length=100), nullable=True)
        batch_op.alter_column('remark', new_column_name='REMARK', existing_type=sa.String(length=100), nullable=True)

        # Recreate the index on the new column name
        batch_op.drop_index('ix_mws_parts_urgent_request_by')
        batch_op.create_index(batch_op.f('ix_mws_parts_URGENT REQUEST BY'), ['URGENT REQUEST BY'], unique=False)
    # ### end Alembic commands ###

    # ### end Alembic commands ###


def downgrade():
    """Reverts column names from UPPERCASE to camelCase/snake_case"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mws_parts', schema=None) as batch_op:
        # Rename all columns back to their original names
        batch_op.alter_column('PART NUMBER', new_column_name='partNumber', existing_type=mysql.VARCHAR(length=100), nullable=False)
        batch_op.alter_column('SERIAL NUMBER', new_column_name='serialNumber', existing_type=mysql.VARCHAR(length=100), nullable=False)
        batch_op.alter_column('TITTLE', new_column_name='tittle', existing_type=mysql.VARCHAR(length=255), nullable=False)
        batch_op.alter_column('JOB TYPE', new_column_name='jobType', existing_type=mysql.VARCHAR(length=100), nullable=True)
        batch_op.alter_column('REF', new_column_name='ref', existing_type=mysql.VARCHAR(length=100), nullable=True)
        batch_op.alter_column('CUSTOMER', new_column_name='customer', existing_type=mysql.VARCHAR(length=100), nullable=True)
        batch_op.alter_column('AC TYPE', new_column_name='acType', existing_type=mysql.VARCHAR(length=100), nullable=True)
        batch_op.alter_column('WBS NO', new_column_name='wbsNo', existing_type=mysql.VARCHAR(length=100), nullable=True)
        batch_op.alter_column('WORKSHEET NO', new_column_name='worksheetNo', existing_type=mysql.VARCHAR(length=100), nullable=True)
        batch_op.alter_column('IWO NO', new_column_name='iwoNo', existing_type=mysql.VARCHAR(length=100), nullable=True)
        batch_op.alter_column('SHOP AREA', new_column_name='shopArea', existing_type=mysql.VARCHAR(length=100), nullable=True)
        batch_op.alter_column('REVISION', new_column_name='revision', existing_type=mysql.VARCHAR(length=50), nullable=True)
        batch_op.alter_column('STATUS', new_column_name='status', existing_type=mysql.VARCHAR(length=50), nullable=True)
        batch_op.alter_column('CURRENT STEP', new_column_name='currentStep', existing_type=mysql.INTEGER(), nullable=True)
        batch_op.alter_column('START DATE', new_column_name='startDate', existing_type=sa.DATE(), nullable=True)
        batch_op.alter_column('FINISH DATE', new_column_name='finishDate', existing_type=sa.DATE(), nullable=True)
        batch_op.alter_column('PREPARED BY', new_column_name='preparedBy', existing_type=mysql.VARCHAR(length=100), nullable=True)
        batch_op.alter_column('PREPARED DATE', new_column_name='preparedDate', existing_type=mysql.VARCHAR(length=100), nullable=True)
        batch_op.alter_column('APPROVED BY', new_column_name='approvedBy', existing_type=mysql.VARCHAR(length=100), nullable=True)
        batch_op.alter_column('APPROVED DATE', new_column_name='approvedDate', existing_type=mysql.VARCHAR(length=100), nullable=True)
        batch_op.alter_column('VERIFIED BY', new_column_name='verifiedBy', existing_type=mysql.VARCHAR(length=100), nullable=True)
        batch_op.alter_column('VERIFIED DATE', new_column_name='verifiedDate', existing_type=mysql.VARCHAR(length=100), nullable=True)
        batch_op.alter_column('IS URGENT', new_column_name='is_urgent', existing_type=mysql.TINYINT(display_width=1), nullable=True)
        batch_op.alter_column('URGENT REQUEST', new_column_name='urgent_request', existing_type=mysql.TINYINT(display_width=1), nullable=True)
        batch_op.alter_column('URGENT REQUEST BY', new_column_name='urgent_request_by', existing_type=mysql.VARCHAR(length=50), nullable=True)
        batch_op.alter_column('MAX STRIPPING DATE', new_column_name='max_stripping_date', existing_type=sa.DATE(), nullable=True)
        batch_op.alter_column('STRIPPING NOTIFIED', new_column_name='stripping_notified', existing_type=mysql.TINYINT(display_width=1), nullable=True)
        batch_op.alter_column('TOTAL DURATION', new_column_name='total_duration', existing_type=mysql.VARCHAR(length=50), nullable=True)
        batch_op.alter_column('CREATED AT', new_column_name='created_at', existing_type=mysql.DATETIME(), nullable=True)
        batch_op.alter_column('UPDATED AT', new_column_name='updated_at', existing_type=mysql.DATETIME(), nullable=True)
        batch_op.alter_column('REF LOGISTIC PPC', new_column_name='ref_logistic_ppc', existing_type=mysql.VARCHAR(length=100), nullable=True)
        batch_op.alter_column('MDR DOC DEFECT', new_column_name='mdr_doc_defect', existing_type=mysql.VARCHAR(length=100), nullable=True)
        batch_op.alter_column('CAPABILITY', new_column_name='capability', existing_type=mysql.VARCHAR(length=100), nullable=True)
        batch_op.alter_column('IWO DATE', new_column_name='iwoDate', existing_type=mysql.VARCHAR(length=100), nullable=True)
        batch_op.alter_column('REMARK MWS', new_column_name='remark_mws', existing_type=mysql.VARCHAR(length=100), nullable=True)
        batch_op.alter_column('TEST RESULT', new_column_name='test_result', existing_type=mysql.VARCHAR(length=100), nullable=True)
        batch_op.alter_column('SCHEDULE DELIVERY ON TIME', new_column_name='schedule_delivery_on_time', existing_type=mysql.VARCHAR(length=100), nullable=True)
        batch_op.alter_column('ECD FINISH WORKDAYS', new_column_name='ecd_finish_workdays', existing_type=mysql.VARCHAR(length=100), nullable=True)
        batch_op.alter_column('SELISIH WORK DAYS', new_column_name='selisih_work_days', existing_type=mysql.VARCHAR(length=100), nullable=True)
        batch_op.alter_column('PROSENTASE SCHEDULE', new_column_name='prosentase_schedule', existing_type=mysql.VARCHAR(length=100), nullable=True)
        batch_op.alter_column('WORKSHEET DATE', new_column_name='workSheetDate', existing_type=mysql.VARCHAR(length=100), nullable=True)
        batch_op.alter_column('FORM OUT NO', new_column_name='form_out_no', existing_type=mysql.VARCHAR(length=100), nullable=True)
        batch_op.alter_column('TANDA TERIMA FO NO', new_column_name='tanda_terima_fo_no', existing_type=mysql.VARCHAR(length=100), nullable=True)
        batch_op.alter_column('TANDA TERIMA FO DATE', new_column_name='tanda_terima_fo_date', existing_type=mysql.VARCHAR(length=100), nullable=True)
        batch_op.alter_column('STRIPPING REPORT DATE', new_column_name='stripping_report_date', existing_type=mysql.VARCHAR(length=100), nullable=True)
        batch_op.alter_column('STRIPPING ORDER BY SAP DATE', new_column_name='stripping_order_by_sap_date', existing_type=mysql.VARCHAR(length=100), nullable=True)
        batch_op.alter_column('PROSENTASE BDP', new_column_name='prosentase_bdp', existing_type=mysql.VARCHAR(length=100), nullable=True)
        batch_op.alter_column('QTY BDP', new_column_name='qty_bdp', existing_type=mysql.VARCHAR(length=100), nullable=True)
        batch_op.alter_column('SELISIH ORDER WORK DAYS', new_column_name='selisih_order_work_days', existing_type=mysql.VARCHAR(length=100), nullable=True)
        batch_op.alter_column('TIME STRIPPING WORK DAYS', new_column_name='time_stripping_work_days', existing_type=mysql.VARCHAR(length=100), nullable=True)
        batch_op.alter_column('TASE STRIPPING', new_column_name='tase_stripping', existing_type=mysql.VARCHAR(length=100), nullable=True)
        batch_op.alter_column('STATUS S US', new_column_name='status_s_us', existing_type=mysql.VARCHAR(length=100), nullable=True)
        batch_op.alter_column('FINISH DATE 2', new_column_name='finish_date2', existing_type=mysql.VARCHAR(length=100), nullable=True)
        batch_op.alter_column('MEN POWERS', new_column_name='men_powers', existing_type=mysql.VARCHAR(length=100), nullable=True)
        batch_op.alter_column('MEN HOURS', new_column_name='men_hours', existing_type=mysql.VARCHAR(length=100), nullable=True)
        batch_op.alter_column('DOCUMENT PENYERTA', new_column_name='document_penyerta', existing_type=mysql.VARCHAR(length=100), nullable=True)
        batch_op.alter_column('SHIP TRANSFER TT DATE', new_column_name='ship_transfer_tt_date', existing_type=mysql.VARCHAR(length=100), nullable=True)
        batch_op.alter_column('SHIP TRANSFER TT NO', new_column_name='ship_transfer_tt_no', existing_type=mysql.VARCHAR(length=100), nullable=True)
        batch_op.alter_column('ISR NO', new_column_name='isrNo', existing_type=mysql.VARCHAR(length=100), nullable=True)
        batch_op.alter_column('SELISIH SHIPPING WORK DAYS', new_column_name='selisih_shipping_work_days', existing_type=mysql.VARCHAR(length=100), nullable=True)
        batch_op.alter_column('TASE', new_column_name='tase', existing_type=mysql.VARCHAR(length=100), nullable=True)
        batch_op.alter_column('REMARK', new_column_name='remark', existing_type=mysql.VARCHAR(length=100), nullable=True)

        # Recreate the index on the old column name
        batch_op.drop_index(batch_op.f('ix_mws_parts_URGENT REQUEST BY'))
        batch_op.create_index('ix_mws_parts_urgent_request_by', ['urgent_request_by'], unique=False)
    # ### end Alembic commands ###
    # ### end Alembic commands ###
