"""Ubah kolom assigned_customer  kembali semula

Revision ID: 908d21255c75
Revises: 42028c611b2a
Create Date: 2025-08-07 11:42:40.305407

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '908d21255c75'
down_revision = '42028c611b2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff_areas', schema=None) as batch_op:
        batch_op.alter_column('assigned_customer',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff_areas', schema=None) as batch_op:
        batch_op.alter_column('assigned_customer',
               existing_type=sa.String(length=100),
               type_=mysql.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
