"""Tambah kolom area dan customer di tabel user

Revision ID: 928949e48add
Revises: adf6630b22b2
Create Date: 2025-08-06 11:43:46.733364

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '928949e48add'
down_revision = 'adf6630b22b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mws_parts', schema=None) as batch_op:
        batch_op.drop_column('assigned_mechanics')
        batch_op.drop_column('assignedTo')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_customer', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('assigned_shop_area', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('assigned_shop_area')
        batch_op.drop_column('assigned_customer')

    with op.batch_alter_table('mws_parts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assignedTo', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('assigned_mechanics', mysql.TEXT(charset='utf8mb4', collation='utf8mb4_0900_ai_ci'), nullable=True))

    # ### end Alembic commands ###
