"""menambahkan kolom MT DATE

Revision ID: 981c7d1e6576
Revises: 9ed37ef04f6c
Create Date: 2025-08-11 19:24:14.359349

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '981c7d1e6576'
down_revision = '9ed37ef04f6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mws_parts', schema=None) as batch_op:
        batch_op.alter_column('PROSENTASE SCHEDULE',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('MEN POWERS',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=50),
               type_=sa.String(length=100),
               existing_nullable=True)

    with op.batch_alter_table('stripping', schema=None) as batch_op:
        batch_op.add_column(sa.Column('MT DATE', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stripping', schema=None) as batch_op:
        batch_op.drop_column('MT DATE')

    with op.batch_alter_table('mws_parts', schema=None) as batch_op:
        batch_op.alter_column('MEN POWERS',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=50),
               existing_nullable=True)
        batch_op.alter_column('PROSENTASE SCHEDULE',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=50),
               existing_nullable=True)

    # ### end Alembic commands ###
