"""Remove targetDate from MwsPart table

Revision ID: a190f994c9d7
Revises: 95058e8fb291
Create Date: 2025-07-28 22:21:19.016175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a190f994c9d7'
down_revision = '95058e8fb291'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mws_parts', schema=None) as batch_op:
        batch_op.drop_column('targetDate')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mws_parts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('targetDate', sa.DATE(), nullable=True))

    # ### end Alembic commands ###
