"""Add planMan and planHours to MwsStep

Revision ID: adf6630b22b2
Revises: 2907a41c525f
Create Date: 2025-08-05 22:03:08.409534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adf6630b22b2'
down_revision = '2907a41c525f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mws_steps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planMan', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('planHours', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mws_steps', schema=None) as batch_op:
        batch_op.drop_column('planHours')
        batch_op.drop_column('planMan')

    # ### end Alembic commands ###
