"""Add urgent_request_by column to MwsPart table

Revision ID: b6bc3cc7dd76
Revises: 2499945aa7f9
Create Date: 2025-08-06 19:57:48.332238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6bc3cc7dd76'
down_revision = '2499945aa7f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mws_parts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('urgent_request_by', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_mws_parts_urgent_request_by'), ['urgent_request_by'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mws_parts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mws_parts_urgent_request_by'))
        batch_op.drop_column('urgent_request_by')

    # ### end Alembic commands ###
