"""Ubah kolom assigned_customer  multiple

Revision ID: f26e8d3a2ad0
Revises: 908d21255c75
Create Date: 2025-08-07 13:16:58.453151

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f26e8d3a2ad0'
down_revision = '908d21255c75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff_areas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_customers', sa.JSON(), nullable=True))
        batch_op.drop_column('assigned_customer')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff_areas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_customer', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=100), nullable=True))
        batch_op.drop_column('assigned_customers')

    # ### end Alembic commands ###
